image: gitpod/workspace-go:latest

vscode:
  extensions:
    - tsandall.opa

tasks:
  - name: Download OPA
    init: >
      curl -L -o opa https://openpolicyagent.org/downloads/v0.52.0/opa_linux_amd64_static &&
      chmod +x opa
  - name: Download conftest
    init: >
      curl -L https://github.com/open-policy-agent/conftest/releases/download/v0.41.0/conftest_0.41.0_Linux_x86_64.tar.gz | tar -xz conftest &&
      chmod +x conftest
